import RPi.GPIO as GPIO
GPIO.setmode(GPIO.BCM)
GPIO.setup(23, GPIO.IN, pull_up_down = GPIO.PUD_DOWN)
GPIO.setup(24, GPIO.IN, pull_up_down = GPIO.PUD_UP)
while True:
    GPIO.wait_for_edge(23, GPIO.RISING)
    print ("Button 1 pressed")
    GPIO.wait_for_edge(23, GPIO.FALLING)
    print ("Button 1 released")
    GPIO.wait_for_edge(24, GPIO.FALLING)
    print ("Button 2 pressed")
    GPIO.wait_for_edge(24, GPIO.RISING)
    print ("Button 2 released")
    exit()
GPIO.cleanup()
